# Generated by Django 2.1.4 on 2018-12-24 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testbatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TestBatch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testexecution',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_name', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TestExecution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testlib',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('path', models.CharField(max_length=160)),
            ],
            options={
                'db_table': 'TestLib',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestsuiteTestcase',
            fields=[
                ('ts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='manager.Testsuite')),
            ],
            options={
                'db_table': 'TestSuite_TestCase',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='tc',
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='testsuite',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
