# Generated by Django 2.1.4 on 2018-12-24 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20181224_1044'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testcase',
            table='TestCase',
        ),
        migrations.AlterModelTable(
            name='testsuite',
            table='TestSuite',
        ),
    ]
