# Generated by Django 2.1.4 on 2019-01-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20190107_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30, unique=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('amenities', models.ManyToManyField(blank=True, to='manager.Amenity')),
            ],
        ),
    ]
