# Generated by Django 2.1.4 on 2019-01-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20190107_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsuite',
            options={'managed': True},
        ),
    ]
