# Generated by Django 2.1.4 on 2019-01-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20190107_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuite',
            name='setting',
        ),
        migrations.AddField(
            model_name='testsuite',
            name='test_case',
            field=models.ManyToManyField(blank=True, to='manager.TestCase'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='author',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
