# Generated by Django 2.1.4 on 2019-01-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20190107_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsuite',
            options={'managed': False},
        ),
    ]
