# Generated by Django 2.1.4 on 2019-01-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20190107_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsuite',
            options={'managed': True},
        ),
    ]
