# Generated by Django 2.1.4 on 2019-01-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20190107_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsuite',
            options={'managed': True},
        ),
    ]
