# Generated by Django 2.1.4 on 2019-01-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20190107_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'managed': True},
        ),
    ]
