# Generated by Django 2.1.4 on 2019-01-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20190108_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='ts',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='test_case',
        ),
        migrations.AddField(
            model_name='testcase',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testcase',
            name='step',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
