# Generated by Django 2.1.4 on 2019-01-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_testsuite_test_case'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsuite',
            options={'managed': False},
        ),
    ]
