# Generated by Django 2.1.4 on 2019-01-07 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_auto_20190108_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsuite',
            options={'managed': True},
        ),
    ]
