# Generated by Django 2.1.4 on 2019-01-08 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_remove_testsuite_test_case'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testexecution',
            options={'managed': True},
        ),
    ]
