# Generated by Django 2.1.4 on 2019-01-08 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_auto_20190108_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testexecution',
            options={'managed': False},
        ),
    ]
