# Generated by Django 2.1.4 on 2019-01-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20190108_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='test_case',
            field=models.ManyToManyField(blank=True, to='manager.TestCase'),
        ),
    ]
