# Generated by Django 2.1.4 on 2019-01-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_testsuite_test_case'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='testsuite',
            options={'managed': False},
        ),
    ]
