# Generated by Django 2.1.4 on 2019-01-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_auto_20190108_1645'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testsuitetestcase',
            table='TestSuite_test_case',
        ),
    ]
